export const SET_SCROLL_LEFT = 'SET_SCROLL_LEFT'
export const SET_SCROLLBAR_Y_VISIBILITY = 'SET_SCROLLBAR_Y_VISIBILITY'
export const SET_IS_EDITING_CELL = 'SET_IS_EDITING_CELL'
export const SET_CURRENT_DRAG = 'SET_CURRENT_DRAG'

export const ADD_TABLE = 'ADD_TABLE'
export const DEL_TABLE = 'DEL_TABLE'

export const SET_DRAG_SOURCE = 'SET_DRAG_SOURCE'
export const SET_DROP_TARGET = 'SET_DROP_TARGET'
export const SET_DRAG_DIRECTION = 'SET_DRAG_DIRECTION'

export const SET_HOVER = 'SET_HOVER'