export const SET_X_SCROLL = 'SET_X_SCROLL'
export const SET_Y_SCROLL_VISIBLE = 'SET_Y_SCROLL_VISIBLE'
export const SET_IS_EDITING_CELL = 'SET_IS_EDITING_CELL'

export const ADD_TABLE = 'ADD_TABLE'
export const DEL_TABLE = 'DEL_TABLE'

export const SET_DRAG_SOURCE = 'SET_DRAG_SOURCE'
export const SET_DROP_TARGET = 'SET_DROP_TARGET'
export const SET_DRAG_DIRECTION = 'SET_DRAG_DIRECTION'